### ISSUE TITLE
Failed to initialize cloud client 'azure' on TC10

### ISSUE THREAD

**Issue by robend** [JetBrains/teamcity-azure-plugin#27]
No images were found due to a error.

Profile Error `Failed to initialize cloud client 'azure'.jetbrains.buildServer.clouds.azure.AzureCloudImage.getAgentPoolId()Ljava/lang/Integer; `
The stacktrace:
`java.lang.AbstractMethodError: jetbrains.buildServer.clouds.azure.AzureCloudImage.getAgentPoolId()Ljava/lang/Integer; 
at jetbrains.buildServer.clouds.server.impl.CloudManagerBaseImpl.createNewClient(CloudManagerBaseImpl.java:284) 
at jetbrains.buildServer.clouds.server.impl.CloudManagerBaseImpl.getClient(CloudManagerBaseImpl.java:252) 
at jetbrains.buildServer.clouds.server.impl.CloudManagerFacade.getClient(CloudManagerFacade.java:110) 
at jetbrains.buildServer.clouds.server.impl.SecuredCloudManager.getClient(SecuredCloudManager.java:73) 
at jetbrains.buildServer.clouds.server.web.beans.CloudTabFormFactoryImpl$CreateProfileInfo.tryCreateInfo(CloudTabFormFactoryImpl.java:71) 
at jetbrains.buildServer.clouds.server.web.beans.CloudTabFormFactoryImpl$CreateProfileInfo.createInfo(CloudTabFormFactoryImpl.java:61) 
at jetbrains.buildServer.clouds.server.web.beans.CloudTabFormFactoryImpl.createProfileInfo(CloudTabFormFactoryImpl.java:47) 
at jetbrains.buildServer.clouds.server.web.beans.CloudTabFormFactoryImpl.getForm(CloudTabFormFactoryImpl.java:41) 
at jetbrains.buildServer.clouds.server.web.admin.CloudAdminController.doGet(CloudAdminController.java:51) 
at jetbrains.buildServer.controllers.BaseFormXmlController.doHandle(BaseFormXmlController.java:60) 
at jetbrains.buildServer.controllers.BaseController.handleRequestInternal(BaseController.java:75) 
at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:147) 
at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:50) 
at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:961) 
at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:895) 
at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:967) 
at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:858) 
at javax.servlet.http.HttpServlet.service(HttpServlet.java:624) 
at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843) 
at javax.servlet.http.HttpServlet.service(HttpServlet.java:731) 
at jetbrains.buildServer.maintenance.TeamCityDispatcherServlet.service(TeamCityDispatcherServlet.java:42) 
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) 
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) 
at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:747) 
at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:603) 
at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:542) 
at org.apache.jasper.runtime.JspRuntimeLibrary.include(JspRuntimeLibrary.java:955) 
at org.apache.jsp.clouds.admin.cloud_002dadmin_002dtab_jsp._jspService(cloud_002dadmin_002dtab_jsp.java:90) 
at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) 
at javax.servlet.http.HttpServlet.service(HttpServlet.java:731) 
at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:439) 
at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395) 
at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339) 
at jetbrains.spring.web.TeamCityJSPServletImpl.access$001(TeamCityJSPServletImpl.java:29) 
at jetbrains.spring.web.TeamCityJSPServletImpl$2.apply(TeamCityJSPServletImpl.java:1) 
at jetbrains.buildServer.util.Util.doUnderContextClassLoader(Util.java:78) 
at jetbrains.spring.web.TeamCityJSPServletImpl.service(TeamCityJSPServletImpl.java:10) 
at javax.servlet.http.HttpServlet.service(HttpServlet.java:731) 
at jetbrains.spring.web.JspController.doHandle(JspController.java:17) 
at jetbrains.buildServer.controllers.BaseController.handleRequestInternal(BaseController.java:75) 
at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:147) 
at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:50) 
at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:961) 
at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:895) 
at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:967) 
at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:858) 
at javax.servlet.http.HttpServlet.service(HttpServlet.java:624) 
at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843) 
at javax.servlet.http.HttpServlet.service(HttpServlet.java:731) 
at jetbrains.buildServer.maintenance.TeamCityDispatcherServlet.service(TeamCityDispatcherServlet.java:42) 
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) 
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) 
at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:747) 
at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:603) 
at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:542) 
at org.apache.jasper.runtime.JspRuntimeLibrary.include(JspRuntimeLibrary.java:955) 
at org.apache.jsp.tag.web.ext.includeExtension_tag._jspx_meth_c_005fif_005f3(includeExtension_tag.java:529) 
at org.apache.jsp.tag.web.ext.includeExtension_tag._jspx_meth_c_005fif_005f0(includeExtension_tag.java:192) 
at org.apache.jsp.tag.web.ext.includeExtension_tag.doTag(includeExtension_tag.java:156) 
at org.apache.jsp.admin.adminMain_jsp._jspx_meth_ext_005fincludeExtension_005f0(adminMain_jsp.java:302) 
at org.apache.jsp.admin.adminMain_jsp.access$6(adminMain_jsp.java:291) 
at org.apache.jsp.admin.adminMain_jsp$Helper.invoke3(adminMain_jsp.java:385) 
at org.apache.jsp.admin.adminMain_jsp$Helper.invoke(adminMain_jsp.java:416) 
at org.apache.jsp.tag.web.page_tag.doTag(page_tag.java:725) 
at org.apache.jsp.admin.adminMain_jsp._jspx_meth_bs_005fpage_005f0(adminMain_jsp.java:183) 
at org.apache.jsp.admin.adminMain_jsp._jspService(adminMain_jsp.java:146) 
at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) 
at javax.servlet.http.HttpServlet.service(HttpServlet.java:731) 
at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:439) 
at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395) 
at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339) 
at jetbrains.spring.web.TeamCityJSPServletImpl.access$001(TeamCityJSPServletImpl.java:29) 
at jetbrains.spring.web.TeamCityJSPServletImpl$2.apply(TeamCityJSPServletImpl.java:1) 
at jetbrains.buildServer.util.Util.doUnderContextClassLoader(Util.java:78) 
at jetbrains.spring.web.TeamCityJSPServletImpl.service(TeamCityJSPServletImpl.java:10) 
at javax.servlet.http.HttpServlet.service(HttpServlet.java:731) 
at jetbrains.spring.web.JspController.doHandle(JspController.java:17) 
at jetbrains.buildServer.controllers.BaseController.handleRequestInternal(BaseController.java:75) 
at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:147) 
at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:50) 
at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:961) 
at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:895) 
at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:967) 
at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:858) 
at javax.servlet.http.HttpServlet.service(HttpServlet.java:624) 
at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843) 
at javax.servlet.http.HttpServlet.service(HttpServlet.java:731) 
at jetbrains.buildServer.maintenance.TeamCityDispatcherServlet.service(TeamCityDispatcherServlet.java:42) 
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) 
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) 
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) 
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) 
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) 
at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:747) 
at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:485) 
at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:410) 
at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:337) 
at org.springframework.web.servlet.view.InternalResourceView.renderMergedOutputModel(InternalResourceView.java:168) 
at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:303) 
at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1246) 
at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1029) 
at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:973) 
at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:895) 
at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:967) 
at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:858) 
at javax.servlet.http.HttpServlet.service(HttpServlet.java:624) 
at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843) 
at javax.servlet.http.HttpServlet.service(HttpServlet.java:731) 
at jetbrains.buildServer.maintenance.TeamCityDispatcherServlet.service(TeamCityDispatcherServlet.java:42) 
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) 
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) 
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) 
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) 
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) 
at jetbrains.buildServer.web.DisableSessionIdFromUrlFilter.doFilter(DisableSessionIdFromUrlFilter.java:8) 
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) 
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) 
at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:107) 
at jetbrains.buildServer.diagnostic.web.DiagnosticFilter.doFilter(DiagnosticFilter.java:45) 
at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:112) 
at jetbrains.buildServer.web.DependencyParametersCalculationContextFilter.doFilter(DependencyParametersCalculationContextFilter.java:1) 
at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:112) 
at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:73) 
at jetbrains.buildServer.web.DelegatingFilter.doFilter(DelegatingFilter.java:2) 
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) 
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) 
at jetbrains.buildServer.web.ResponseFragmentFilter.doFilter(ResponseFragmentFilter.java:23) 
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) 
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) 
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220) 
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122) 
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169) 
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103) 
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) 
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436) 
at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078) 
at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625) 
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1757) 
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1716) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) 
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) 
at java.lang.Thread.run(Thread.java:745)`

**Comment by robend** [comment]
Downloaded new plugin and it works.
