### ISSUE TITLE
Plugin settings page fails to fetch options

### ISSUE THREAD

**Issue by PashaPash** [JetBrains/teamcity-azure-plugin#28]
- Installed azure-classic plugin
- Created new cloud profile
- Entered subscription id and management certificate

Fetching options... indicator appeared, changed to red
> Unable to fetch options: Internal Server Error

The following error is logged to teamcity-winservice.log on each page refresh:

```
[2016-08-01 13:45:48,242] console                           [Info] [2016-08-01 13:45:48,169]  ERROR - jdeferred.impl.AbstractPromise - an uncaught exception occured in a DoneCallback
[2016-08-01 13:45:48,242] console                           [Info] java.lang.NullPointerException
[2016-08-01 13:45:48,242] console                           [Info] 	at jetbrains.buildServer.clouds.azure.asm.connector.AzureApiConnector$4.pipeDone(AzureApiConnector.java:284)
[2016-08-01 13:45:48,242] console                           [Info] 	at jetbrains.buildServer.clouds.azure.asm.connector.AzureApiConnector$4.pipeDone(AzureApiConnector.java:277)
[2016-08-01 13:45:48,242] console                           [Info] 	at org.jdeferred.impl.PipedPromise$3.onDone(PipedPromise.java:33)
[2016-08-01 13:45:48,242] console                           [Info] 	at org.jdeferred.impl.AbstractPromise.triggerDone(AbstractPromise.java:107)
[2016-08-01 13:45:48,242] console                           [Info] 	at org.jdeferred.impl.AbstractPromise.triggerDone(AbstractPromise.java:98)
[2016-08-01 13:45:48,242] console                           [Info] 	at org.jdeferred.impl.DeferredObject.resolve(DeferredObject.java:70)
[2016-08-01 13:45:48,242] console                           [Info] 	at org.jdeferred.DeferredFutureTask.done(DeferredFutureTask.java:83)
[2016-08-01 13:45:48,242] console                           [Info] 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:384)
[2016-08-01 13:45:48,242] console                           [Info] 	at java.util.concurrent.FutureTask.set(FutureTask.java:233)
[2016-08-01 13:45:48,242] console                           [Info] 	at java.util.concurrent.FutureTask.run(FutureTask.java:274)
[2016-08-01 13:45:48,242] console                           [Info] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[2016-08-01 13:45:48,242] console                           [Info] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[2016-08-01 13:45:48,242] console                           [Info] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[2016-08-01 13:45:48,242] console                           [Info] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[2016-08-01 13:45:48,242] console                           [Info] 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by PashaPash** [comment]
Apparently, that was caused by a classic cloud service hosted in the same subscription.

Classic (package-based) cloud services have no ```<OSVirtualHardDisk>``` element in ```<HostedService>```, so plugin fails to enumerate Images / VMs if at least one package-based could service exists in subsciption
