### ISSUE TITLE
Show nicer error message when deployment fails

### ISSUE THREAD

**Issue by matt-richardson** [JetBrains/teamcity-azure-plugin#38]
I just had an issue where I ran into an out of cores error, but the only information in the log was:

```
Failed to create deployment in resource group Win-2016-163: 400 is not a valid polling status code 
com.microsoft.azure.CloudException: 400 is not a valid polling status code: The template deployment 'Win-2016-163' is not valid according to the validation procedure. The tracking id is '8f60e8be-fa0b-4fa3-8bc7-da7116d22ea9'. See inner errors for details. Please see https://aka.ms/arm-deploy for usage details.
	at com.microsoft.azure.AzureClient.getPutOrPatchResultAsync(AzureClient.java:185)
	at com.microsoft.azure.management.resources.DeploymentsOperationsImpl$10.onResponse(DeploymentsOperationsImpl.java:410)
	at retrofit2.OkHttpCall$1.callSuccess(OkHttpCall.java:135)
	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:114)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:133)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Unfortunately, the inner errors are not displayed, so you cant tell what the problem is.

Only after finding the template on github, pasting it into the azure portal and guessing at the parameters was I able to see the actual error.

In the logs, it would be useful to:
a) show the actual template submitted
b) show the parameters submitted
c) show the inner errors

**Comment by dtretyakov** [comment]
@matt-richardson, thanks for your contribution.

**Comment by matt-richardson** [comment]
Thanks for merging so quickly, @dtretyakov!

One thing I noted, it's showing my contribution in TeamCity as somebody else?

![image](https://cloud.githubusercontent.com/assets/373389/18370541/2c77ae10-7671-11e6-92c4-5870265f87e0.png)

**Comment by dtretyakov** [comment]
@matt-richardson, yeah, teamcity tried to match your username in commit and found some other `%matt%` profile created at teamcity.jetbrains.com
