### ISSUE TITLE
`Failed to create deployment in resource group XXXXX: Async operation failed`

### ISSUE THREAD

**Issue by matt-richardson** [JetBrains/teamcity-azure-plugin#44]
Agents are failing to be created due to `Async operation failed`. Would be nice to handle this situation better, or at least log information about what the actual problem is and how I can fix it.

```
[2016-10-07 06:46:29,460]   WARN [l-1983-thread-1] - ouds.azure.arm.AzureCloudImage - Failed to create deployment in resource group tcwin2016-85: Async operation failed 
jetbrains.buildServer.clouds.CloudException: Failed to create deployment in resource group tcwin2016-85: Async operation failed
    at jetbrains.buildServer.clouds.azure.arm.connector.AzureApiConnectorImpl$17.failure(AzureApiConnectorImpl.java:639)
    at com.microsoft.azure.AzureClient$PutPatchPollingTask.run(AzureClient.java:848)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: com.microsoft.rest.ServiceException: Async operation failed
    ... 8 more
```

**Comment by pbiasotti** [comment]
We are experiencing the same issue. Is there any ETA for this fix?

**Comment by dtretyakov** [comment]
@matt-richardson, @pbiasotti, could you please try to update to the latest ARM plugin version and try to start new cloud build agent again?
https://plugins.jetbrains.com/plugin/9260?pr=teamcity

**Comment by pbiasotti** [comment]
@dtretyakov We downloaded and tested the new version and worked fine. Thanks for your help!

**Comment by dtretyakov** [comment]
@pbiasotti, great, that now it works fine.
