### ISSUE TITLE
Agent idle time not reset after shutdown

### ISSUE THREAD

**Issue by SaphuA** [JetBrains/teamcity-azure-plugin#52]
Note that I'm not sure if this is a plugin or TeamCity issue.

We were having weird issues with our agents where TeamCity would start/stop them randomly and way too often. After investigating teamcity-clouds.log we think the issue is that the idle time is not reset after shutting down an agent, causing a cycle of shutting the agent down immediately after starting it.

Here's the log for a single agent. I've marked the messages about idle time with **'s.

```
[2017-05-09 13:50:49,665]   INFO [onPool-worker-0] - ouds.azure.arm.AzureCloudImage - Creating new virtual machine contoso-build6 

[2017-05-09 14:18:44,197]   INFO [17-05-09 14:04)] - uds.base.AbstractCloudInstance - Changing contoso-build6(fdaca8) status from Unknown to Running  
[2017-05-09 14:18:45,202]   INFO [17-05-09 14:04)] - .server.impl.CloudEventsLogger - Cloud instance entered 'running' state, profile 'Azure Resource Manager'{id=arm-1, projectId=_Root}, AzureCloudInstance{myName='contoso-build6'} 
[2017-05-09 14:18:48,955]   INFO [jectId=_Root} 2] - louds.base.AbstractCloudClient - Cloud profile 'profile 'Azure Resource Manager'{id=arm-1, projectId=_Root}' initialized 
[2017-05-09 14:19:12,666]   INFO [p-nio-80-exec-6] - r.impl.DBCloudStateManagerImpl - Image: AzureCloudImage{myName='contoso-build'}, profile: profile 'Azure Resource Manager'{id=arm-1, projectId=_Root} was marked to CONTAIN agent 
[2017-05-09 14:19:12,759]   INFO [p-nio-80-exec-6] - .server.impl.CloudEventsLogger - Detected cloud agent "contoso-build6" {id=3}, profile 'Azure Resource Manager'{id=arm-1, projectId=_Root}, AzureCloudInstance{myName='contoso-build6'} 

**[2017-05-09 15:07:46,898]   INFO [uled executor 3] - te.IdleTimeoutTerminateFactory - Will terminate instance AzureCloudInstance{myName='contoso-build6'}, profile 'Azure Resource Manager'{id=arm-1, projectId=_Root} with idle time 30 minutes (idle time is 30 minutes) 
[2017-05-09 15:07:46,898]   INFO [uled executor 3] - l.instances.StopInstanceAction - Terminating instance: AzureCloudInstance{myName='contoso-build6'}, profile 'Azure Resource Manager'{id=arm-1, projectId=_Root}, reason: After 30 minutes idle 
[2017-05-09 15:07:46,898]   INFO [uled executor 3] - r.impl.DBCloudStateManagerImpl - Image: AzureCloudImage{myName='contoso-build'}, profile: profile 'Azure Resource Manager'{id=arm-1, projectId=_Root} was marked to CONTAIN agent 
[2017-05-09 15:07:46,929]   INFO [uled executor 3] - uds.base.AbstractCloudInstance - Changing contoso-build6(fdaca8) status from Running to Scheduled to stop  
[2017-05-09 15:07:47,674]   INFO [onPool-worker-1] - ouds.azure.arm.AzureCloudImage - Stopping virtual machine contoso-build6 
[2017-05-09 15:07:50,526]   INFO [uled executor 5] - .server.impl.CloudEventsLogger - Cloud instance entered 'scheduled to stop' state, profile 'Azure Resource Manager'{id=arm-1, projectId=_Root}, AzureCloudInstance{myName='contoso-build6'} 
[2017-05-09 15:08:00,236]   INFO [p-nio-80-exec-9] - ces.terminate.AgentRemoverImpl - Removing cloud agent "contoso-build6" {id=3} because: Instance has been terminated. AzureCloudInstance{myName='contoso-build6'}, profile 'Azure Resource Manager'{id=arm-1, projectId=_Root} 
[2017-05-09 15:08:00,408]   INFO [p-nio-80-exec-9] - .server.impl.CloudEventsLogger - Cloud agent Unregistered agent "contoso-build6" {id=3} is no longer recognized as cloud agent because instance has gone: profileId=arm-1, imageId=contoso-build, instanceId=contoso-build6 
[2017-05-09 15:08:00,408]   INFO [p-nio-80-exec-9] - ces.terminate.AgentRemoverImpl - Removing cloud agent Unregistered agent "contoso-build6" {id=3} because: Cloud instance (id=contoso-build6, imageId=contoso-build, profileId=arm-1) has gone (is not reported by cloud profile) 
[2017-05-09 15:10:48,433]   INFO [onPool-worker-1] - uds.base.AbstractCloudInstance - Changing contoso-build6(fdaca8) status from Scheduled to stop to Stopped  
[2017-05-09 15:10:48,433]   INFO [onPool-worker-1] - ouds.azure.arm.AzureCloudImage - Virtual machine contoso-build6 has been successfully terminated 
[2017-05-09 15:10:50,809]   INFO [uled executor 5] - .server.impl.CloudEventsLogger - Cloud instance entered 'stopped' state, profile 'Azure Resource Manager'{id=arm-1, projectId=_Root}, AzureCloudInstance{myName='contoso-build6'} 

[2017-05-10 07:02:55,643]   INFO [17-05-10 06:56)] - uds.base.AbstractCloudInstance - Changing contoso-build6(18e2813) status from Unknown to Stopped  
[2017-05-10 07:02:55,770]   INFO [17-05-10 06:56)] - .server.impl.CloudEventsLogger - Cloud instance entered 'stopped' state, profile 'Azure Resource Manager'{id=arm-1, projectId=_Root}, AzureCloudInstance{myName='contoso-build6'} 
[2017-05-10 07:02:57,136]   INFO [jectId=_Root} 2] - louds.base.AbstractCloudClient - Cloud profile 'profile 'Azure Resource Manager'{id=arm-1, projectId=_Root}' initialized 

[2017-05-10 08:03:30,619]   INFO [0 Flush Queue 1] - .instances.StartInstanceAction - Starting cloud instance: profile 'Azure Resource Manager'{id=arm-1, projectId=_Root}, AzureCloudImage{myName='contoso-build'}, hash=xxx, reason=Automatic start: Compatible with queued build Contoso :: Portal :: Build, Package & Push(promotionId=157) 
[2017-05-10 08:03:31,344]   INFO [onPool-worker-1] - uds.base.AbstractCloudInstance - Changing contoso-build6(18e2813) status from Stopped to Scheduled to start  
[2017-05-10 08:03:31,346]   INFO [onPool-worker-1] - ouds.azure.arm.AzureCloudImage - Starting stopped virtual machine contoso-build6 
[2017-05-10 08:03:31,363]   INFO [0 Flush Queue 1] - .instances.StoppedInstanceTask - Instance has changed status from stopped to Scheduled to start: AzureCloudInstance{myName='contoso-build6'}, profile 'Azure Resource Manager'{id=arm-1, projectId=_Root} 
[2017-05-10 08:03:31,364]   INFO [0 Flush Queue 1] - .server.impl.CloudEventsLogger - Cloud instance start succeeded: profile 'Azure Resource Manager'{id=arm-1, projectId=_Root}, AzureCloudInstance{myName='contoso-build6'} 
[2017-05-10 08:03:32,497]   INFO [uled executor 2] - .server.impl.CloudEventsLogger - Cloud instance entered 'scheduled to start' state, profile 'Azure Resource Manager'{id=arm-1, projectId=_Root}, AzureCloudInstance{myName='contoso-build6'} 
**[2017-05-10 08:03:55,862]   INFO [uled executor 2] - te.IdleTimeoutTerminateFactory - Will terminate instance AzureCloudInstance{myName='contoso-build6'}, profile 'Azure Resource Manager'{id=arm-1, projectId=_Root} with idle time 61 minutes (idle time is 30 minutes) 
[2017-05-10 08:03:55,863]   INFO [uled executor 2] - l.instances.StopInstanceAction - Terminating instance: AzureCloudInstance{myName='contoso-build6'}, profile 'Azure Resource Manager'{id=arm-1, projectId=_Root}, reason: After 30 minutes idle 
[2017-05-10 08:03:55,863]   INFO [uled executor 2] - r.impl.DBCloudStateManagerImpl - Image: AzureCloudImage{myName='contoso-build'}, profile: profile 'Azure Resource Manager'{id=arm-1, projectId=_Root} was marked to CONTAIN agent 
[2017-05-10 08:03:55,899]   INFO [uled executor 2] - uds.base.AbstractCloudInstance - Changing contoso-build6(18e2813) status from Scheduled to start to Scheduled to stop  
[2017-05-10 08:03:56,002]   INFO [6 Flush Queue 1] - .instances.StartInstanceAction - Starting cloud instance: profile 'Azure Resource Manager'{id=arm-1, projectId=_Root}, AzureCloudImage{myName='contoso-build'}, hash=xxx, reason=Automatic start: Compatible with queued build Contoso :: Portal :: Build, Package & Push(promotionId=157) 
[2017-05-10 08:03:57,504]   INFO [uled executor 3] - .server.impl.CloudEventsLogger - Cloud instance entered 'scheduled to stop' state, profile 'Azure Resource Manager'{id=arm-1, projectId=_Root}, AzureCloudInstance{myName='contoso-build6'} 
[2017-05-10 08:06:33,135]   INFO [onPool-worker-1] - ouds.azure.arm.AzureCloudImage - Stopping virtual machine contoso-build6 
[2017-05-10 08:09:34,219]   INFO [onPool-worker-1] - uds.base.AbstractCloudInstance - Changing contoso-build6(18e2813) status from Scheduled to stop to Stopped  
[2017-05-10 08:09:34,219]   INFO [onPool-worker-1] - ouds.azure.arm.AzureCloudImage - Virtual machine contoso-build6 has been successfully terminated 
[2017-05-10 08:09:37,569]   INFO [uled executor 3] - .server.impl.CloudEventsLogger - Cloud instance entered 'stopped' state, profile 'Azure Resource Manager'{id=arm-1, projectId=_Root}, AzureCloudInstance{myName='contoso-build6'} 

[2017-05-10 12:13:26,146]   INFO [7 Flush Queue 1] - .instances.StoppedInstanceTask - Instance has changed status from stopped to Scheduled to start: AzureCloudInstance{myName='contoso-build6'}, profile 'Azure Resource Manager'{id=arm-1, projectId=_Root} 
[2017-05-10 12:13:26,146]   INFO [7 Flush Queue 1] - .server.impl.CloudEventsLogger - Cloud instance start succeeded: profile 'Azure Resource Manager'{id=arm-1, projectId=_Root}, AzureCloudInstance{myName='contoso-build6'} 
[2017-05-10 12:13:26,294]   INFO [onPool-worker-0] - ouds.azure.arm.AzureCloudImage - Starting stopped virtual machine contoso-build6 
[2017-05-10 12:13:26,397]   INFO [uled executor 1] - .server.impl.CloudEventsLogger - Cloud instance entered 'scheduled to start' state, profile 'Azure Resource Manager'{id=arm-1, projectId=_Root}, AzureCloudInstance{myName='contoso-build6'} 
**[2017-05-10 12:13:57,269]   INFO [uled executor 3] - te.IdleTimeoutTerminateFactory - Will terminate instance AzureCloudInstance{myName='contoso-build6'}, profile 'Azure Resource Manager'{id=arm-1, projectId=_Root} with idle time 244 minutes (idle time is 30 minutes) 
[2017-05-10 12:13:57,269]   INFO [uled executor 3] - l.instances.StopInstanceAction - Terminating instance: AzureCloudInstance{myName='contoso-build6'}, profile 'Azure Resource Manager'{id=arm-1, projectId=_Root}, reason: After 30 minutes idle 
[2017-05-10 12:13:57,269]   INFO [uled executor 3] - r.impl.DBCloudStateManagerImpl - Image: AzureCloudImage{myName='contoso-build'}, profile: profile 'Azure Resource Manager'{id=arm-1, projectId=_Root} was marked to CONTAIN agent 
[2017-05-10 12:13:57,300]   INFO [uled executor 3] - uds.base.AbstractCloudInstance - Changing contoso-build6(18e2813) status from Scheduled to start to Scheduled to stop  
[2017-05-10 12:13:57,516]   INFO [7 Flush Queue 1] - .instances.StartInstanceAction - Starting cloud instance: profile 'Azure Resource Manager'{id=arm-1, projectId=_Root}, AzureCloudImage{myName='contoso-build'}, hash=xxx, reason=Automatic start: Compatible with queued build Contoso :: Portal :: Build, Package & Push(promotionId=159) 
[2017-05-10 12:14:01,419]   INFO [uled executor 1] - .server.impl.CloudEventsLogger - Cloud instance entered 'scheduled to stop' state, profile 'Azure Resource Manager'{id=arm-1, projectId=_Root}, AzureCloudInstance{myName='contoso-build6'}
```

**Comment by dtretyakov** [comment]
@SaphuA, thanks for reporting. Could you please share TeamCity and Azure ARM plugin versions, idle timeout and terminate conditions in your cloud profile if they are available.

**Comment by SaphuA** [comment]
@dtretyakov Sure!

TeamCity version: TeamCity 2017.1.1 (build 46654)
ARM Plugin version: 0.5.2
Idle timeout: 30 minutes
Terminate conditions: none

**Comment by SaphuA** [comment]
Okay so because the issue above isn't workable at all we changed our idle time to _empty_ and enabled the _terminate condition after the first build_.

We now have the exact same issue of an endless loop where TC starts a VM and immediatly shuts it down after booting. Except this time because the agent reports it has done a build.
`[2017-05-11 07:49:42,692]   INFO [uled executor 5] - l.instances.StopInstanceAction - Terminating instance: AzureCloudInstance{myName='contoso-build2'}, profile 'Azure Resource Manager'{id=arm-1, projectId=_Root}, reason: After the first build `

**Comment by SaphuA** [comment]
@dtretyakov Any updates? Should I contact TeamCity support instead? This is a major issue for us since we now have to manually start/stop VM's.

**Comment by dtretyakov** [comment]
@SaphuA, sorry for delay, currently investigating it, will share result soon.

**Comment by dtretyakov** [comment]
@SaphuA, it seems that I figured out what may happens. 

Do you use VHD images with TeamCity Build Agent 10.0.x to start build agents? If so it may take a lot of time to upgrade build agent and plugins to TeamCity 2017.1.1 version. Then when agent after upgrade connects to the TeamCity server it shuts down due to idle timeout. When TeamCity detects outdated cloud build agent image it displays exclamation mark:
![image](https://cloud.githubusercontent.com/assets/1025927/26162259/ea6d8d40-3b2e-11e7-82ba-530948771508.png)


In this case we recommend to use source VHD image with pre-installed TeamCity 2017.1.1 build agent.
Also "Reuse allocated virtual machines" option in cloud profile settings can reduce cold start time.

**Comment by dtretyakov** [comment]
@SaphuA, also I've added reset for start date for new instances, could you please try to use [following plugin build](https://teamcity.jetbrains.com/viewLog.html?buildId=1070440&buildTypeId=TeamcityAzurePlugin_BuildResourceManager&tab=artifacts) to check if it solves the problem?

**Comment by SaphuA** [comment]
Hi @dtretyakov , we actually already had these issues before updating TeamCity and hoped updating might resolve them. So while it's true that the agent is running on an older version, I'm pretty sure it is not the cause for our issues.

Also the logs seem to indicate some kind of resetting issue and not a startup issue.

Updating the agent image is on our todo list anyway so I'll report back _if_ it changes anything.

**Comment by dtretyakov** [comment]
@SaphuA, you are right, later I realized that the agent upgrade is not the cause, it just delays first start.
Did you tried to use last plugin build to check whether it addresses this problem?

**Comment by SaphuA** [comment]
I just wanted to try your version of the plugin, but when I try to change settings for the cloud profile I get an alert box with the exception below.

Could this have to do with the updated azure java sdk?

```
Trace: java.lang.NoClassDefFoundError: jetbrains/buildServer/clouds/azure/arm/AzureCloudClientFactory$getPropertiesProcessor$1
	at jetbrains.buildServer.clouds.azure.arm.AzureCloudClientFactory.getPropertiesProcessor(AzureCloudClientFactory.kt:97)
	at jetbrains.buildServer.clouds.server.web.admin.CloudProfileFormAction.createPropertiesProcessor(CloudProfileFormAction.java:113)
	at jetbrains.buildServer.clouds.server.web.admin.CloudProfileFormAction.processProfileAction(CloudProfileFormAction.java:67)
	at jetbrains.buildServer.clouds.server.web.project.CloudEditProfileController.processAction(CloudEditProfileController.java:121)
	at jetbrains.buildServer.clouds.server.web.project.CloudEditProfileController.doPost(CloudEditProfileController.java:115)
	at jetbrains.buildServer.clouds.server.web.project.CloudEditProfileController.doPost(CloudEditProfileController.java:109)
	at jetbrains.buildServer.controllers.BaseFormXmlController$1.handleRequest(BaseFormXmlController.java:54)
	at jetbrains.buildServer.controllers.AjaxRequestProcessor.processRequest(AjaxRequestProcessor.java:45)
	at jetbrains.buildServer.controllers.BaseFormXmlController.doHandle(BaseFormXmlController.java:52)
	at jetbrains.buildServer.controllers.BaseController.handleRequestInternal(BaseController.java:75)
	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:147)
	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:50)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:961)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:895)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:967)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:869)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at jetbrains.buildServer.maintenance.TeamCityDispatcherServlet.processedByMainServlet(TeamCityDispatcherServlet.java:50)
	at jetbrains.buildServer.maintenance.TeamCityDispatcherServlet.service(TeamCityDispatcherServlet.java:46)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at jetbrains.buildServer.web.jsp.JspPrecompilerFilter.doFilter(JspPrecompilerFilter.java:129)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at jetbrains.buildServer.web.DisableSessionIdFromUrlFilter.doFilter(DisableSessionIdFromUrlFilter.java:5)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:107)
	at jetbrains.buildServer.diagnostic.web.DiagnosticFilter.doFilter(DiagnosticFilter.java:84)
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:112)
	at jetbrains.buildServer.web.DependencyParametersCalculationContextFilter.doFilter(DependencyParametersCalculationContextFilter.java:2)
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:112)
	at jetbrains.buildServer.web.CSRFFilter.doFilter(CSRFFilter.java:100)
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:112)
	at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:73)
	at jetbrains.buildServer.web.DelegatingFilter.doFilter(DelegatingFilter.java:37)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at jetbrains.buildServer.web.ResponseFragmentFilter.doFilter(ResponseFragmentFilter.java:5)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1757)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1716)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by SaphuA** [comment]
It seems to be working, but if you don't mind I'll leave the ticket open for another week just to be sure.

Thanks @dtretyakov

**Comment by SaphuA** [comment]
It seems to be resolved, thanks @dtretyakov
