### ISSUE TITLE
`Failed to create deployment in resource group XXXXX: Async operation failed`

### ISSUE THREAD

**Issue by catalystjs** [JetBrains/teamcity-azure-plugin#54]
This issue is now present again in TeamCity 2017.1.3. I updated to the latest snapshot, but I am still getting the same error. Is this something that is currently known?

`
[2017-07-28 12:55:50,809]   WARN [onPool-worker-1] - ouds.azure.arm.AzureCloudImage - Failed to create deployment in resource group prtnrblda-1: Async operation failed with provisioning state: Failed
Async operation failed with provisioning state: Failed: jetbrains.buildServer.clouds.CloudException: Failed to create deployment in resource group prtnrblda-1: Async operation failed with provisioning state: Failed
Async operation failed with provisioning state: Failed 
[2017-07-28 12:55:50,810]  DEBUG [onPool-worker-1] - ouds.azure.arm.AzureCloudImage - Failed to create deployment in resource group prtnrblda-1: Async operation failed with provisioning state: Failed
Async operation failed with provisioning state: Failed 
jetbrains.buildServer.clouds.CloudException: Failed to create deployment in resource group prtnrblda-1: Async operation failed with provisioning state: Failed
Async operation failed with provisioning state: Failed
	at jetbrains.buildServer.clouds.azure.arm.connector.AzureApiConnectorImpl$createDeploymentAsync$1.doResume(AzureApiConnectorImpl.kt:384)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resumeWithException(CoroutineImpl.kt:60)
	at kotlinx.coroutines.experimental.DispatchedContinuation$resumeWithException$1.run(CoroutineDispatcher.kt:152)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
`

**Comment by dtretyakov** [comment]
@catalystjs, thanks for reporting. Could you please update to the [latest plugin build](https://teamcity.jetbrains.com/viewType.html?buildTypeId=TeamcityAzurePlugin_BuildResourceManager) where was fixed root cause logging of Azure deployment errors?

**Comment by dtretyakov** [comment]
@catalystjs, if it still fails to create vm in the latest plugin build, please report the updated entry from the `teamcity-clouds.log` file, where was improved root cause logging.
