### ISSUE TITLE
Failed to delete deployment

### ISSUE THREAD

**Issue by thinkbeforecoding** [JetBrains/teamcity-azure-plugin#79]
When agents have been idle for enough time they should be deallocated, but the agent enters an Error state:
```
Failed to delete deployment buildagent-1 in resource group TeamCity: null: jetbrains.buildServer.clouds.CloudException: Failed to delete deployment buildagent-1 in resource group TeamCity: null (enable debug to see stacktrace) 
[2017-11-30 13:51:10,611]   INFO [onPool-worker-1] - uds.base.AbstractCloudInstance - Changing buildagent-1(7cedc0) status from Scheduled to stop to Error 
```
It seems it's trying to delete totally the deployment even if the 'Reuse allocated virtual machines' option is set.

TeamCity version: 2017A
Plugin Version: 0.6.4

**Comment by thinkbeforecoding** [comment]
A more precise stackframe
```
jetbrains.buildServer.clouds.CloudException: Failed to delete deployment buildagent-1 in resource group TeamCity: nulljetbrains.buildServer.clouds.CloudException: Failed to delete deployment buildagent-1 in resource group TeamCity: null 
at jetbrains.buildServer.clouds.azure.arm.connector.AzureApiConnectorImpl$deleteDeploymentAsync$1.doResume(AzureApiConnectorImpl.kt:599) 
at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54) 
at kotlinx.coroutines.experimental.DispatchTask.run(CoroutineDispatcher.kt:120) 
at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) 
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) 
at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) 
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) 
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) 
Caused by: java.lang.NullPointerException 
at jetbrains.buildServer.clouds.azure.arm.connector.AzureApiConnectorImpl$deleteDeploymentAsync$1$doResume$$inlined$withLock$lambda$1.doResume(AzureApiConnectorImpl.kt:567) 
at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54) 
at kotlinx.coroutines.experimental.DispatchTask.run(CoroutineDispatcher.kt:120) 
at kotlinx.coroutines.experimental.EventLoopBase$QueuedRunnableTask.run(EventLoop.kt:189) 
at kotlinx.coroutines.experimental.EventLoopBase.processNextEvent(EventLoop.kt:129) 
at kotlinx.coroutines.experimental.BlockingCoroutine.joinBlocking(Builders.kt:225) 
at kotlinx.coroutines.experimental.BuildersKt.runBlocking(Builders.kt:150) 
at kotlinx.coroutines.experimental.BuildersKt.runBlocking$default(Builders.kt:142) 
at jetbrains.buildServer.clouds.azure.arm.connector.AzureApiConnectorImpl$deleteDeploymentAsync$1.doResume(AzureApiConnectorImpl.kt:561) 
...
```

**Comment by dtretyakov** [comment]
@thinkbeforecoding, thanks for reporting. Could you please also specify what type of image you use: template, VHD or image?

**Comment by thinkbeforecoding** [comment]
It's a template.
The template deployment was successfully  deployed.
I don't use agent push, the arm template use the arm CustomScript extension to install the agent after the machine is built. The agent is installed, started and authorized correctly.

**Comment by thinkbeforecoding** [comment]
I installed the snapshot.
The error disappeared, and the agent have been deleted.
But is it expected when the 'Reuse allocated virtual machines ' box is checked ? Shouldn't they be only deallocated instead of deleted ?

**Comment by thinkbeforecoding** [comment]
Another strange thing.
I put a limit of 5 for the image.
When 4 agents have been depolyed, the 'start' button is still enabled, but when I press it, it add a new 'build agent' line but no actual deployment is started. When I refresh the page, this fifth agent doesn't appear anymore.

**Comment by dtretyakov** [comment]
@thinkbeforecoding, could you please share the `teamcity-clouds.log` [server log file](https://confluence.jetbrains.com/display/TCDL/TeamCity+Server+Logs) for investigation?
GitHub does not have secure attachments, so could you please file an issue in the [TeamCity tracker](https://youtrack.jetbrains.com/issues/TW) and attach it there?

**Comment by thinkbeforecoding** [comment]
Ah.. looking at the teamcity-clouds.log I see that the 5th is not allocated because I reached the core limit on the subscription. My bad 😁

**Comment by thinkbeforecoding** [comment]
But stopping the agent still delete the VM instead of just stopping them...

**Comment by thinkbeforecoding** [comment]
The log says:
```
Removing virtual machine buildagent-3 due to cloud image settings 
```
Which, in the code seems to indicate that `behaviour.isDeleteAfterStop` is true, which is only the case for
  `FRESH_CLONE(true, false)`.
but in `AzureCloudDetails.kt', `getBehaviour()` is implemented as:
```
 if (myReuseVm) CloneBehaviour.ON_DEMAND_CLONE else CloneBehaviour.FRESH_CLONE
```
So it seems that myReuseVM is false, even if the check box is checked.

Is there a name mismatch in parameters  for `const val REUSE_VM = "reuseVm"` ?

I cannot find on the server where the cloud profile + template parameters are stored ? any clue ?

**Comment by thinkbeforecoding** [comment]
I found the parameter in the config and it is true...
```
       <param name="reuseVm" value="true" />
 ```
So.... Don't know what is the source of the problem... 🤔

**Comment by thinkbeforecoding** [comment]
I'll create a specific issue for this

**Comment by dtretyakov** [comment]
@thinkbeforecoding, great thanks for investigation, will take a look at the issue #80.
